server.port=8081
spring.application.name=demo
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/edutracker?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=2400032371
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
# 'update' tells Spring to automatically create or update your database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect